name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  nix-instantiate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
      - name: Check Nix parsing
        run: |
          nix-shell --run evalnix

  nixpkgs-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check Nix formatting
        run: |
          nix-shell --run "fmt --check"
